[[config]]
name = "default"
os   = "ubuntu"

[[config.ci-steps]]
command = "cargo check --all-targets"

[[config.ci-steps]]
command = "cargo clippy --all-targets -- -D warnings"

[[config.ci-steps]]
command = "cargo test --all-targets"
