exclude = [".direnv/**", "target/**"]
include = [
    "Cargo.toml",
    "bcode.toml",
    "clippier.toml",
    "clippy.toml",
    "deny.toml",
    "rust-toolchain.toml",
    "taplo.toml",
    "worktree.config.toml",
]

[formatting]
align_entries  = true
indent_string  = "    "
reorder_arrays = false
reorder_keys   = true
